-- Common Chinese grocery shelf-life defaults (fridge unless noted).
-- Agent may override from packaging / user knowledge.

INSERT OR IGNORE INTO food_knowledge
  (name, name_norm, aliases_json, category, fridge_days, freezer_days, pantry_days, default_location, notes)
VALUES
  ('生菜', '生菜', '["油麦菜","罗马生菜","leaf lettuce"]', 'veg', 2, NULL, NULL, 'fridge', '易蔫，2天内吃完'),
  ('菠菜', '菠菜', '["spinach"]', 'veg', 2, NULL, NULL, 'fridge', NULL),
  ('小白菜', '小白菜', '["青菜"]', 'veg', 3, NULL, NULL, 'fridge', NULL),
  ('白菜', '白菜', '["大白菜"]', 'veg', 7, NULL, NULL, 'fridge', NULL),
  ('西兰花', '西兰花', '["花椰菜","broccoli"]', 'veg', 4, 30, NULL, 'fridge', NULL),
  ('西红柿', '西红柿', '["番茄","tomato"]', 'veg', 5, NULL, 3, 'counter', '未熟可室温'),
  ('黄瓜', '黄瓜', '["cucumber"]', 'veg', 5, NULL, NULL, 'fridge', NULL),
  ('土豆', '土豆', '["马铃薯","potato"]', 'veg', NULL, NULL, 14, 'pantry', '避光干燥'),
  ('洋葱', '洋葱', '["onion"]', 'veg', NULL, NULL, 21, 'pantry', NULL),
  ('大蒜', '大蒜', '["garlic"]', 'veg', NULL, NULL, 30, 'pantry', NULL),
  ('胡萝卜', '胡萝卜', '["carrot"]', 'veg', 14, NULL, NULL, 'fridge', NULL),
  ('豆腐', '豆腐', '["tofu"]', 'veg', 3, 30, NULL, 'fridge', '开封当天到次日'),
  ('蘑菇', '蘑菇', '["香菇","金针菇"]', 'veg', 4, 30, NULL, 'fridge', NULL),
  ('苹果', '苹果', '["apple"]', 'fruit', 14, NULL, 7, 'fridge', NULL),
  ('香蕉', '香蕉', '["banana"]', 'fruit', NULL, NULL, 4, 'counter', '不要冷藏整根'),
  ('草莓', '草莓', '["strawberry"]', 'fruit', 2, 30, NULL, 'fridge', '极易坏'),
  ('葡萄', '葡萄', '["grape"]', 'fruit', 5, NULL, NULL, 'fridge', NULL),
  ('橙子', '橙子', '["脐橙","orange"]', 'fruit', 14, NULL, 7, 'fridge', NULL),
  ('西瓜', '西瓜', '["watermelon"]', 'fruit', 3, NULL, 5, 'fridge', '切开必须冷藏，3天'),
  ('鸡胸', '鸡胸', '["鸡胸肉","chicken breast"]', 'meat', 2, 60, NULL, 'fridge', '生鲜2天，否则冷冻'),
  ('鸡肉', '鸡肉', '["鸡腿","chicken"]', 'meat', 2, 60, NULL, 'fridge', NULL),
  ('猪肉', '猪肉', '["排骨","pork"]', 'meat', 2, 60, NULL, 'fridge', NULL),
  ('牛肉', '牛肉', '["牛排","beef"]', 'meat', 3, 90, NULL, 'fridge', NULL),
  ('培根', '培根', '["bacon"]', 'meat', 7, 30, NULL, 'fridge', NULL),
  ('鸡蛋', '鸡蛋', '["egg"]', 'dairy', 21, NULL, 7, 'fridge', NULL),
  ('牛奶', '牛奶', '["milk"]', 'dairy', 5, NULL, NULL, 'fridge', '看盒上日期'),
  ('酸奶', '酸奶', '["yogurt"]', 'dairy', 7, NULL, NULL, 'fridge', NULL),
  ('奶酪', '奶酪', '["cheese"]', 'dairy', 14, 60, NULL, 'fridge', NULL),
  ('三文鱼', '三文鱼', '["salmon"]', 'seafood', 1, 30, NULL, 'fridge', '当天或次日'),
  ('虾', '虾', '["shrimp","基围虾"]', 'seafood', 1, 30, NULL, 'fridge', NULL),
  ('面包', '面包', '["bread"]', 'staple', 4, 30, 2, 'counter', NULL),
  ('米饭', '米饭', '["剩饭"]', 'leftover', 1, 14, NULL, 'fridge', '隔夜饭当天吃'),
  ('剩菜', '剩菜', '["leftover"]', 'leftover', 2, 14, NULL, 'fridge', NULL),
  ('矿泉水', '矿泉水', '["水","water"]', 'drink', NULL, NULL, 365, 'pantry', '不必提醒过期'),
  ('冰水', '冰水', '[]', 'drink', 3, NULL, NULL, 'fridge', '手动添加常见'),
  ('冰茶', '冰茶', '["红茶","绿茶"]', 'drink', 3, NULL, NULL, 'fridge', NULL),
  ('果汁', '果汁', '["juice"]', 'drink', 5, NULL, NULL, 'fridge', '开封后3天'),
  ('啤酒', '啤酒', '["beer"]', 'drink', 90, NULL, 90, 'fridge', NULL);
